### ISSUE TITLE
Handle Configuration Changes

### ISSUE THREAD

**Issue by IbrahimYousre** [IbrahimYousre/Resume-Builder#1]
The current version of the app works only in portrait mode. The user would have a better experience, if he can use the app in whatever orientation he likes.

**Comment by TPS** [comment]
To be specific, if _opened_ forced in landscape mode (e.g., via accessibility options/apps), the app works fine, but any orientation change crashes it (without any real consequence, since all data stays saved, so that's just an irritation).

_Thanks for the app!  It's 1 of very few open-source Android résumé-building apps I could find, & I very much like its simplicity.  I've a few ideas I'll RFE via issues shortly._

**Comment by IbrahimYousre** [comment]
Thank @TPS  for time you have spent with the app you have provided me with great feedback. Please, feel welcome to contribute to the app as much as you want.
